name: Build and Deploy Typst HTML to GitHub Pages

on:
  push:
    branches: [ main ]  # Adjust branch name as needed
  workflow_dispatch:  # Allow manual triggering

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Fontist
        uses: fontist/setup-fontist@v2
      
      - name: Install fonts
        run: |
          fontist install "Fira Sans"
          fontist install "Libertinus"
          fontist install "Fira Code"
      
      - name: Setup Typst
        uses: typst-community/setup-typst@v4
        with:
          typst-version: ^0.13.1
      
      - name: Compile Typst to HTML
        run: |
          typst compile thesis.typ index.html \
            --font-path ~/.fontist/fonts \
            --features html
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4